### PR TITLE
Fitb and mchoice fixes

### PR DESCRIPTION
**Pull request by bjones1**
This is a bunch of fixes, along with better testing, of the fitb and mchoice directives.

One change: the JS no longer reports "Correct" or "Incorrect" for multiple choice questions -- it lets the color tell the story; authors can always add these terms if they prefer.

### CODE REVIEW

**Comment by bnmnetp** [comment]
All tests still pass on master but when I run the tests on this branch, I get 

```
======================================================================
ERROR: runestone.activecode.test.test_activecode (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runestone.activecode.test.test_activecode
Traceback (most recent call last):
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/millbr02/src/Runestone/RunestoneComponents/runestone/activecode/test/test_activecode.py", line 7, in <module>
    setUpModule, tearDownModule = module_fixture_maker(__file__)
ValueError: too many values to unpack (expected 2)


======================================================================
ERROR: runestone.clickableArea.test.test_clickableArea (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runestone.clickableArea.test.test_clickableArea
Traceback (most recent call last):
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/millbr02/src/Runestone/RunestoneComponents/runestone/clickableArea/test/test_clickableArea.py", line 9, in <module>
    setUpModule, tearDownModule = module_fixture_maker(__file__)
ValueError: too many values to unpack (expected 2)


======================================================================
ERROR: runestone.dragndrop.test.test_dragndrop (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runestone.dragndrop.test.test_dragndrop
Traceback (most recent call last):
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/millbr02/src/Runestone/RunestoneComponents/runestone/dragndrop/test/test_dragndrop.py", line 15, in <module>
    setUpModule, tearDownModule = module_fixture_maker(__file__)
ValueError: too many values to unpack (expected 2)


======================================================================
ERROR: runestone.poll.test.test_poll (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runestone.poll.test.test_poll
Traceback (most recent call last):
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/millbr02/src/Runestone/RunestoneComponents/runestone/poll/test/test_poll.py", line 3, in <module>
    setUpModule, tearDownModule = module_fixture_maker(__file__)
ValueError: too many values to unpack (expected 2)


======================================================================
ERROR: runestone.question.test.test_question (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runestone.question.test.test_question
Traceback (most recent call last):
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/millbr02/src/Runestone/RunestoneComponents/runestone/question/test/test_question.py", line 3, in <module>
    setUpModule, tearDownModule = module_fixture_maker(__file__)
ValueError: too many values to unpack (expected 2)


======================================================================
ERROR: runestone.reveal.test.test_reveal (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runestone.reveal.test.test_reveal
Traceback (most recent call last):
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/millbr02/src/Runestone/RunestoneComponents/runestone/reveal/test/test_reveal.py", line 9, in <module>
    setUpModule, tearDownModule = module_fixture_maker(__file__)
ValueError: too many values to unpack (expected 2)


======================================================================
ERROR: runestone.shortanswer.test.test_shortanswer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runestone.shortanswer.test.test_shortanswer
Traceback (most recent call last):
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/millbr02/src/Runestone/RunestoneComponents/runestone/shortanswer/test/test_shortanswer.py", line 9, in <module>
    setUpModule, tearDownModule = module_fixture_maker(__file__)
ValueError: too many values to unpack (expected 2)


======================================================================
ERROR: runestone.tabbedStuff.test.test_tabbedStuff (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runestone.tabbedStuff.test.test_tabbedStuff
Traceback (most recent call last):
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/millbr02/anaconda/envs/runedev/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/millbr02/src/Runestone/RunestoneComponents/runestone/tabbedStuff/test/test_tabbedStuff.py", line 9, in <module>
    setUpModule, tearDownModule = module_fixture_maker(__file__)
ValueError: too many values to unpack (expected 2)

```

It looks like module_fixture_maker now returns more values??

**Comment by bjones1** [comment]
Oops, I forgot to include a fix in my lp branch. I'll push that, which should fix everything.

**Comment by bjones1** [comment]
All tests pass on my PC now.

**Comment by bnmnetp** [comment]
Yep, they all pass for me now too.

**Comment by bjones1** [comment]
Great, thanks for taking a look!

**Comment by bjones1** [comment]
Thanks!

**Pull request merged**
