### PR TITLE
Auto load history for activecode problems on page load

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
Remove "Load History" button completely
Load historyscrubber on activecode problem initialization

### CODE REVIEW

**Comment by ascholerChemeketa** [comment]
Proposed changes for experiment with automatically loading history for activecode problems.

**Comment by bnmnetp** [comment]
This looks good except for in a timed exam.  Yeah welcome to my world -- timed exams have always been problematic.  In a timed exam we show the slider from the start but only show them the first thing in the history.  Now we are getting double sliders.

Screen Shot 2022-09-08 at 4 56 46 PM

**Comment by bnmnetp** [comment]
The overview book has a couple of timed exams you can play with.

**Comment by bnmnetp** [comment]
I see ---

See the `timedInit` function in `TimedActiveCodeMixin` where I already have the call `await this.addHistoryScrubber(true);`

**Comment by bnmnetp** [comment]
No need for you to do anything... I just removed that call and everything looks good.

I don't think there is any reason to worry about `awaiting` it when we load the page and are initializing everything.  I think I was just doing that for timed exams to be careful.

**Comment by bnmnetp** [comment]
OK, this will be live on Saturday.  We will know a lot by Monday morning.

**Pull request merged**
