### PR TITLE
Activecode download button

### PR DESCRIPTION
**Pull request by kooi**
Added the ":enabledownload:" flag to the activecode directive to enable Blob download of activecode data.
(issue #510 )

Currently automatically names the file as "<activecode-id>_<reversedate>.py" 
`var fileName = fnb + '_' + d.toJSON().substring(0,10).split('-').join('')+'.py';`

(only activecode.py and activecode.js should be changed; setup.py is only edited for checking purposes)

### CODE REVIEW

**Comment by bnmnetp** [comment]
Thanks for this.

It looks like you have a couple of conflicts to clean up.  And some extraneous console.log messages to get rid of.

On a different level, this seems like the kind of thing where a global flag such as ``eBookConfig.downloadsEnabled`` would be useful.  If an option was specified on the directive explicitly then that should take precedence, but if no options was there either way then letting the instructor enable/disable this for everything would be really nice.

**Comment by kooi** [comment]
A global flag seems like a good idea, I'll get on that.

**Comment by kooi** [comment]
I think I enabled the global flag correctly, though I'm not entirely sure but it does seem to work for me.
I also read the now implement the correct default file extension based on the Activecode language setting.

**Comment by bnmnetp** [comment]
Well done, thank you.

I will accept this now.  It may take a couple of days to update thinkcspy and then update the website so that folks could enable this for their courses.

**Pull request merged**
