### PR TITLE
Fix: logCurrentAnswer is async!

### PR DESCRIPTION
**Pull request by bjones1**

### CODE REVIEW

**Comment by bnmnetp** [comment]
Interesting... Was this causing a problem for you?  In neither case are we looking at the response. So I'm curious.

**Comment by bjones1** [comment]
I used the response in the dynamic problems flavor of fitb questions, which is what led me to this fix. So, these recent PRs are prep  for upcoming dynamic problems -- I'm looking for places where PRs help Runestone and don't break anything to make the later PRs easier to digest.

**Comment by bjones1** [comment]
This PR depends on #1309, which needs to be merged before this can pass.

**Comment by bjones1** [comment]
@bnmnetp, this is ready for review.

**Comment by bnmnetp** [comment]
OK, this seems pretty simple.

**Pull request merged**
