### PR TITLE
Added a retake option to the timed exams

### PR DESCRIPTION
**Pull request by ericsonga**
I want some timed exams to allow learners to retake them.  While Tyler had added a reset button it was only showing if the user had skipped all the multiple choice questions on a timed exams.  This gives the author more control over if the timed exam can be retaken.

### CODE REVIEW

**Comment by bnmnetp** [comment]
Barb, when last we talked, you tried this out before your experiment but it wasn't working.  Does this still need more work or have you fixed it and are happy with it now?

**Comment by ericsonga** [comment]
No, I haven't had time to work on this yet.  It will have to wait till after my defense.

**Comment by bnmnetp** [comment]
@ericsonga would be great to get this cleaned up and merged this summer.  Or if you don't intend to go back to it, we should close it.

**Comment by bnmnetp** [comment]
This PR is obsolete with recent work on timed exams.

**Pull request closed without merging**
