### PR TITLE
Add support for Proof Blocks

### PR DESCRIPTION
**Pull request by SethPoulsen**
Add support for a directed acyclic graph (DAG) based grader to the Parson's problem plugin, so that it can support Proof Blocks problems (https://www.proofblocks.org/).

### CODE REVIEW

**Comment by SethPoulsen** [comment]
@barbarer @bnmnetp I thought you might like to glance at what I have going so far before we meet next week.

There are a few big TODOs in here still, but I think I've made some progress in the right direction.

**Comment by SethPoulsen** [comment]
@bnmnetp From my end, I think this is all ready to go. Feel free to review & test. 

Thanks!

**Comment by SethPoulsen** [comment]
Thanks @rbeezer and @bnmnetp!

One thing I forgot to mention--we have another feature in PrairieLearn called "block groups", which adds an extra condition to the grading where a subset of blocks must appear contiguously in the answer. This is helpful for doing things like Proof by Cases.

see an example here: https://github.com/PrairieLearn/PrairieLearn/blob/5dddcfb5b5ccc302790905c6ef165559a26e15ca/exampleCourse/questions/demo/proofBlocks/question.html#L35-L60

If people are interested in this, I can look in to adding the feature here as well. I'm not sure how the syntax would work with the Runestone markdown files, but with PreTeXt markup it could obviously be done similarly to the PrairieLearn example.

**Comment by bnmnetp** [comment]
@SethPoulsen I have been telling people that RST will soon come to the point where we will add new features to the components, but those features will only be available when you are writing in PreTeXt.  As far as I am concerned this could be one of those features.

The PR would need to update the javascript and the html representation but would not need to provide RST markup.

**Comment by SethPoulsen** [comment]
Hi Rob, these are great questions. 
  
  In PrairieLearn, leaving the `depends` attribute off is equivalent to `depends=""`, so the line does not depend on anything. I think this makes the most sense. 
  
  > Are the depends inside a pl-block-group redundant

  No---they are important. Each pl-block-group can have an arbitrarily complex DAG inside it (See, for example the test case all the way at the bottom of this currently open PR if you want to see a more complex example: https://github.com/PrairieLearn/PrairieLearn/pull/5871/files)

Hopefully that answer's your questions. If not, I'm happy to come by the drop-in, but I'm busy the next couple of Fridays, so it would have to be in a couple of weeks.

Thanks!

**Comment by bnmnetp** [comment]
@rbeezer and @SethPoulsen 

I think block groups are going to be important for code too.

I was just having a discussion with @ascholerChemeketa on slack and he gave the folowing example

```
def a(): #tag 0; depend:;
=====
    return 10 #tag 1; depends:0;
=====
def b(): #tag 2; depends:;
=====
    return 20 #tag 3; depends:2;
=====
print(a + b) #tag 4; depends1,3;
```

There is nothing to prevent

```
def a():
def b():
  return 10
  return 20
print(a + b)
```
as a correct answer without the block groups.

**Comment by bnmnetp** [comment]
Maybe a syntax like:

```
~begin-group~  tag g1 depend:;
def a(): #tag 0; depend:;
=====
    return 10 #tag 1; depends:0;
=====
~end-group~
~begin-group~ #tag g2 depends:;
def b(): #tag 2; depends:;
=====
    return 20 #tag 3; depends:2;
=====
~end-group~
print(a + b) #tag 4; depends g1,g2;
```

Ugh, that is not pretty.

**Comment by bnmnetp** [comment]
Or this idea from Andrew is a lot less ugly.

```
def a(): #tag 0; group: g1; depend:;
=====
    return 10 #tag 1; group: g1; depends:0;
=====
def b(): #tag 2; group: g2; depends:;
=====
    return 20 #tag 3; group: g2; depends:2;
=====
print(a + b) #tag 4; depends g1,g2;
```

**Comment by ascholerChemeketa** [comment]
Here is a slightly more complicated sample with nested groups. 

For purposes of programming problems, I think the rst syntax could be simplified to something like below. `under` would imply both a dependency and define a group. That amount of info looks compatible with the  `group_belonging` needed by the Prairie Learn algorithm.

```
def a(): #tag 0;
=====
    print("In a") #tag 2; under: 0;
=====
    if(True): #tag 3; under: 0;
=====
        x = 10 #tag 4; under: 3;
=====
        y = 20 #tag 5; under: 3;
=====
    return x + y #tag 6; under: 0; depends: 2,3;
=====
def b(): #tag 7;
=====
    return 20 #tag 8; under: 2;
=====
print(a() + b()) #tag 9; depends: 0,7;
```

**Comment by SethPoulsen** [comment]
Ah, these are very interesting examples! Most people I work with only do single-function code blocks in parson's problems, so I hadn't thought of this use case.

Some comments on people's suggestions: 
I think that the `under` shorthand syntax suggested by @ascholerChemeketa is cool, I'm all for making things shorter when possible, but it seems to not be as flexible. For example, what if there was a block group where multiple different lines could be the first line in the block, I don't see a way to express that. 

The markup suggested by @rbeezer is essentially what we do in PrairieLearn, so it looks good to me. 

To be honest, I can't think of a syntax for block groups in the rst markup that both looks pretty and gives full support to the features. Maybe a slight improvement to @bnmnetp original suggestion could be to collapse of the group delimiters onto the same lines as the block delimiters, something like: 

```
~begin-group~  #tag g1 depend:;
def a(): #tag 0; depend:;
=====
    return 10 #tag 1; depends:0;
===== ~begin-group~ #tag g2 depends:;
def b(): #tag 2; depends:;
=====
    return 20 #tag 3; depends:2;
===== ~end-group~
print(a + b) #tag 4; depends g1,g2;
```
I am also curious though about how long the rst markup is going to be supported.

**Comment by bnmnetp** [comment]
@Seth - so as I understand it you have code for this, (except for the runestone markup) we just need to agree on some markup for RST ?

I'm good with doing something simple, like what @ascholerChemeketa suggested as the long term solution is really PreTeXt.   

I'm not sure what makes the most sense.  We are in a kind of middle ground of moving to PreTeXt but there are books that are not yet converted, and cannot be converted because we are waiting on some other component to move to PreTeXt. 

0. I think PreTeXt markup is as Rob suggests... -  the issue is how it ends up looking in the html
1. use `under` to keep the current implementation fairly simple.  Assuming its easy for Rob to generate.
2. use a more complicated markup which makes parsing more complicated in the js -- seems bad considering we want to ditch 
3. Use parsons as a test case for going straight to json.  We would still want to generate the json for backward compatibility but it probably would not be that hard?
  * I'm suddenly imagining a way of specifying a parsons problem that looks like:

```
.. parsonsprob:: uniqueid
    :asptx:
    
    <exercise label="number-theory-proof" adaptive="yes">
   <title>Early morning exercise</title>
   <statement>
       <p>Put the blocks in order.</p>
   </statement>
   <blocks>
       <block order="2">
           <p>Get Up</p>
       </block>
       <block order="3">
           <choice><p>Drink a shot of rum</p></choice>
           <choice correct="yes"><p>Eat Breakfast</p></choice>
       </block>
       <block order="1">
           <p>Brush your teeth</p>
       </block>
   </blocks>
   <hint>Drinking before noon is not recommended.</hint>
</exercise>
    
```

Generating the json is now easy...

**Comment by SethPoulsen** [comment]
Sorry no, I haven't yet implemented block groups in the JavaScript grader. That will take some amount of work. 

Are you suggesting we just essentially stick the PreTeXt markup into the HTML and have that traversed by the javascript? This seems like a find solution to me.

**Comment by rbeezer** [comment]
> Use parsons as a test case for going straight to json. We would still want to generate the json for backward compatibility but it probably would not be that hard?

Not sure if matters to me or not: but I think Parson's was the most complicated thing I had to interpret;  math/code, numbered/not, indented/not, and maybe more.  I would suggest multiple-choice as a good first test case.

**Pull request merged**
