### PR TITLE
Bug Fixes - Parsons problems heights, widths, and image displays (Vincent Qiu September 2020)

### PR DESCRIPTION
**Pull request by vqum**
Many Parsons problem areas were displaying with significantly more height than necessary taking up more screen space and with less width than necessary causing lines of text to overflow. Now calculations for Parsons problem areas heights and widths have been reprogrammed within parsons.js to resolve this issue.

Some Parsons problems include images (e.g. https://runestone.academy/runestone/books/published/StudentCSP/CSPRepeatTurtles/patterns.html) that cause misalignment of the problem text and Parsons problem areas. Now images are being checked for and , if found, are being moved to their own <div> within parsons.js, and the new <div> has a corresponding class within parsons.css to resolve this issue.

additional commit on September 18, 2020:
Incorporated William Li's changes to parsons.js from previous pull request: https://github.com/RunestoneInteractive/RunestoneComponents/pull/1051

### CODE REVIEW

**Comment by barbarer** [comment]
I approve these changes.

**Comment by barbarer** [comment]
I approve the latest change too.

**Comment by vqum** [comment]
Apologies if I'm misunderstanding since I'm new to working with Runestone and with GitHub, but it appears that the check failed on a multiple choice question, is that correct? None of the commits that I submitted should affect the functionality of multiple choice problems since the files modified are parsons.js and parsons.css for Parsons problem functionality.

image

**Comment by bnmnetp** [comment]
Well,  when the tests are passing on the master branch but not on your branch that is usually an indicator that you should:

1. Make sure your branch is up to date with master by doing a merge or rebase.
2. You may have inadvertently broken something 
3. Occasionally timing issues creep in and tests fail, but if the tests are run again they pass. It is a good idea to run `pytest`  from your local machine.  `pip install requirements-dev.txt` to get the prerequisites.  that way you know if they are going to pass before you push to GitHub.

I cannot accept pull requests that are not passing.

Github has good documentation on how you can make an "upstream remote" so that you can bring in changes from master to your own branch.

**Comment by vqum** [comment]
Making sure my branch is up to date with master:
`git remote -v`
'git status'
`git fetch upstream`
`git checkout master`
`git merge upstream/master`
image

The details of the failed check (https://github.com/RunestoneInteractive/RunestoneComponents/pull/1074/checks?check_run_id=1135036495) do show a fail for python3.7 but a pass for python3.8
image

Running `pytest` locally for `runestone\parsons\test`:
- 4 consecutive runs with no failures
image

Running `pytest` locally specifically for the failed check using `runestone\mchoice\test`:
-  1st run a failure mirroring that of the failed check `FAILED test_assess.py::MultipleChoiceQuestion_Tests::test_mc2 - AssertionError: 'alert-info' not found in ''`
- 2nd run immediately after with no failures
- 3rd run immediately after with no failures
- 4th run immediately after with a different failure `FAILED test_assess.py::MultipleChoiceQuestion_Tests::test_mc3 - selenium.common.exceptions.StaleElementReferenceExce...`
- 5th run immediately after with no failures
image
image

**Pull request merged**
