### PR TITLE
Changed the timed exam to not show the "Finish Exam" button till all questions have been visited

### PR DESCRIPTION
**Pull request by barbarer**
I deleted the .DS_Store files from the repo too.

People kept clicking on the "Finish Exam" when they had not answered any questions or just one.  Now it will not show that button until the user has visited (displayed) every question.

### CODE REVIEW

**Comment by bnmnetp** [comment]
The unit tests for this are failing.  Maybe the test needs to be updated to reflect this new behavior.

But, are you sure this is a good thing?  What if a student runs out of time before they have seen all the questions?  they will have no way of submitting.

**Comment by barbarer** [comment]
If they run out of time it will save their answers.

I have never done anything with the test cases.  Can you walk me through
that?

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
Sure you will want to look at `test_fitb.py` that is where there are unit tests for the timed exam.  Not very many of them to be sure...

The function is test_timed

You will see that there are python function calls that fill in the blank or click on buttons.  The general idea is to find something by its id and then call the click function on it. 

So you will need to update the tests to click through each question before submitting.

**Comment by barbarer** [comment]
I updated the test to work (I hope).  I am not sure how to run the test.

**Comment by bnmnetp** [comment]
Instructions for running the tests are covered in the main README.rst.  I just now made a couple of updates to that.

You can also let Travis-CI run the tests and if they fail click on the Details link (see above) to see what failed.

**Comment by bnmnetp** [comment]
Here's the message for the latest test run:

```
>       self.assertIn("Num Correct: 2", timed_results)
566E       AssertionError: 'Num Correct: 2' not found in 'Num Correct: 1. Questions: 1\nNum Wrong: 1. Questions: 2\nNum Skipped: 0. Questions: None\nPercent Correct: 50%'
567
568test_fitb.py:210: AssertionError
```

**Comment by barbarer** [comment]
Fixed the test case to be just one correct.

**Pull request merged**
