### PR TITLE
Fix: Detect and report duplicate IDs.

### PR DESCRIPTION
**Pull request by bjones1**
Clean: DRY code -- consolidate self.options['divid'] = self.arguments[0].

This passes all unit tests and builds thinkcspy with no problems, but it does produce a number of warnings. For example:

```
E:\Runestone\web2py\applications\runestone\books\thinkcspy\_sources\ClassesDiggingDeeper\Exercises.rst:91: WARNING: Duplicate ID -- see E:\Runestone\web2py\applications\runestone\books\thinkcspy\_sources\ClassesBasics\Exercises.rst, line 85
E:\Runestone\web2py\applications\runestone\books\thinkcspy\_sources\ClassesDiggingDeeper\Exercises.rst:160: WARNING: Duplicate ID -- see E:\Runestone\web2py\applications\runestone\books\thinkcspy\_sources\ClassesBasics\Exercises.rst, line 158
E:\Runestone\web2py\applications\runestone\books\thinkcspy\_sources\ClassesDiggingDeeper\Exercises.rst:219: WARNING: Duplicate ID -- see E:\Runestone\web2py\applications\runestone\books\thinkcspy\_sources\ClassesBasics\Exercises.rst, line 209
E:\Runestone\web2py\applications\runestone\books\thinkcspy\_sources\Functions\thinkcspyExercises.rst:57: WARNING: Duplicate ID -- see E:\Runestone\web2py\applications\runestone\books\thinkcspy\_sources\Dictionaries\Exercises.rst, line 51
```

Looking at the first example, [_sources\ClassesBasics\Exercises.rst line 91](https://github.com/RunestoneInteractive/thinkcspy/blame/master/_sources/ClassesDiggingDeeper/Exercises.rst#L88) (actually line 88 -- there are 3 lines added by the [rst_prolog in conf.py](https://github.com/RunestoneInteractive/thinkcspy/blob/master/conf.py#L99) is:

```
           .. actex:: classes_q3
```

while [_sources\ClassesBasics\Exercises.rst, line 85](https://github.com/RunestoneInteractive/thinkcspy/blame/master/_sources/ClassesBasics/Exercises.rst#L82) (actually 82) is:

```
           .. actex:: classes_q3
```

So, it is detecting actual problems (unless I misunderstand that the divid must be globally unique). I've certainly been bitten by copying and pasting a question and forgetting to change the divid, and hope this will help detect and avoid this.

### CODE REVIEW

**Comment by bnmnetp** [comment]
I fixed the conflict with the now removed livecode.py.

I like this a lot, but I wonder if we should upgrade the warning to an error.  At least in the case where we are actively adding components to a database, having two components with the same id in the same project really is an error.

**Comment by bjones1** [comment]
Thanks! Yes, I agree that the warning should become an error -- I was a bit conservative on this when first authoring it. It's saved me a bunch of times from silly mistakes.

**Comment by bnmnetp** [comment]
Thanks, I'll do it this afternoon.

**Comment by bjones1** [comment]
Thanks!

**Pull request merged**
