### PR TITLE
Updates to CSS etc to support docutils 0.17

### PR DESCRIPTION
**Pull request by bnmnetp**
This is an initial attempt to update styling for docutils 0.17.1

The major change by docutils was to move from `<div class="section">` to using the semantic tag `<section>` for structuring the document.

I have taken a different approach to the top level styling in this PR.  This selector `.container .section>*:not(.section):not(.ac_section)` has been the bane of my existence for years!  It basically constrains the width of everything in the section to be a sensible reading width.  Leaving the various components feeling more or less cramped when they could really use more space.  I have replaced that with the following selector

```
#main-content section > p,
#main-content section > pre,
#main-content section > table,
#main-content section > ul,
#main-content section > ol,
#main-content section > dl,
#main-content section > h1,
#main-content section > h2,
#main-content section > h3,
#main-content section > h4,
#main-content section > .admonition,
#main-content section > .toctree-wrapper {
```

Naming the tags explicitly may not be the best and we may need to add more tags to it over time but it leaves us free to style the components at whatever width we want!  Using good discretion so that the resulting page doesn't look like a hodgepodge.

This is a branch based on the rs2ptx branch, so it depends on it a little. but we can accept rs2ptx without needing to accept this one.

### CODE REVIEW

**Comment by bnmnetp** [comment]
@ascholerChemeketa What do you think of this approach?  My CSS is not elegant and maybe you know of a better way to gives us the flexibility I would like.

**Comment by bjones1** [comment]
Is this still relevant, or did it effectively get merged already?

**Comment by bnmnetp** [comment]
No I merged the PR from @ascholerChemeketa

**Comment by bnmnetp** [comment]
He had a much better solution so disregard what I had proposed.

**Pull request closed without merging**
