### PR TITLE
Language added: spanish ("es")

### PR DESCRIPTION
**Pull request by Kikolo3000**

### CODE REVIEW

**Comment by bnmnetp** [comment]
Hi, I appreciate this PR very much.

Could you have a look at remaking the PR against the webpack branch?  I'm going to merge that to master in another week and it has a lot of things moved around and reformatted. -- the javascript especially.

**Comment by Kikolo3000** [comment]
Done!

**Comment by bnmnetp** [comment]
One important aspect of the webpack branch is that we use webpack to create one big runestone.js file.  That makes the add_i8n_js calls obsolete.  The translation files should be added by using an import statement in the main js file for that component.  See for example fitb.js or activecode.js

The .py files won't need to be changed then, and that will resolve the conflicts.

**Comment by bnmnetp** [comment]
Noooo, you deleted activecode.py and others... they can't be deleted you just need to restore them to their original state.

**Comment by bnmnetp** [comment]
Sorry, I'm going to close this.  I would welcome the spanish translations, so please resubmit.

**Pull request closed without merging**
