### PR TITLE
Dropdown menu fixes

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
Fix two minor but visually annoying layout issues in top of page dropdowns.

Padding of items inside social menu ("Runestone in social media", "Help support us", and Donate button)
Display of search button next to text input inside search menu

### CODE REVIEW

**Comment by ascholerChemeketa** [comment]
Note for Brad - adding one more fix to the dark/light slider... still in progress.

**Comment by ascholerChemeketa** [comment]
Added the Dark Mode fix. Think this is done now.

**Comment by bnmnetp** [comment]
Thanks, I will get it reviewed in the next day or two.

**Comment by bnmnetp** [comment]
Thanks!  the dark mode toggle looks much nicer!  I knew there had to be a way to do that.

I had not noticed that the search was broken either.  I copied that change to the server code so its fixed there now too... Thanks

**Pull request merged**
