### PR TITLE
Added timed support for ignorable elements: activecode and short answer

### PR DESCRIPTION
**Pull request by flysaiah**
"Ignorable" timed components are now allowed in timed, which means that any handgraded components such as short answer or activecode can now be part of a timed exam.

### CODE REVIEW

**Comment by flysaiah** [comment]
I just found a few bugs with parsons and activecode with respect to local storage--I will reopen this when I fix them.

**Comment by flysaiah** [comment]
Due to the fact that parsons evaluation involves selecting DOM elements via their ID's, parsons currently can't be made into a timed component as timed assessments hide each component when it is not the current question. Because of this, parsons only evaluated correctly when it is on-screen during evaluation, so the parsons support has been reverted in this PR.

**Comment by bnmnetp** [comment]
@flysaiah, can you pull the latest and fix the conflicts.

But before you do, can you verify if you are seeing the problem with parsons problems where a multi-line block is not getting indented correctly in the rendered parsons problem.  It seems like we fix this problem but it keeps on coming back.

Brad

**Comment by flysaiah** [comment]
I just tested the multiline parsons problems using the one in #113 as an example, and everything seems to work fine.

**Comment by bnmnetp** [comment]
Isaiah,  I grabbed your PR into my test environment, but when I build, I get this:

screenshot 2016-05-12 16 23 55

The only thing I can think of is that it is related to not logging in.  Refresh my memory, does the rendering of the timed exam stuff rely on a login event?

**Comment by flysaiah** [comment]
It does--I'm unable to replicate your problem for some reason, but I'm fairly certain it's because the runestone:login-complete isn't getting triggered in bookfuncs.js. I added some triggers that cover the missing cases that I see, which I think should fix the problem you're seeing. If that doesn't work, please send me some details about your test environment so I can replicate the problem and more precisely address it.

**Pull request merged**
