### PR TITLE
Fix indentation handling for DAG based Parsons problems

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
Indentation check code in line based grader assumes strict ordering. Break it into function for DAG grader to override.

DAG grader assumes every block has a tag and uses that to look up proper indentation in the given solution.

### CODE REVIEW

**Comment by ascholerChemeketa** [comment]
Checking on failed tests...

**Comment by ascholerChemeketa** [comment]
Modified "tag" parsing code to allow multicharacter tags

Improved to handle non-sequentially numbered tags

Added a test and updated existing tests to remove deprecated constructs

**Comment by ascholerChemeketa** [comment]
@bnmnetp I think this is ready... it is passing parsons tests.

hparsons tests are failing. It appears they are running on the Parsons test webpage instead of their own. I tried rolling back to a commit before my own changes and I am still seeing the same behavior. It looks like you are currently making changes in hparson... I don't *think* that the failed test is based on my code.

**Comment by bnmnetp** [comment]
No, the failed test is a simple wording change.  For math problems that use parsons it does not make any sense to call the solution "program" so we agreed on the more general term of "answer"

**Comment by bnmnetp** [comment]
Why do you think they are running on the Parsons test webpage?  When I run this locally I can see the page in the chrome browser and they are defilnitely horizontal problems.

**Comment by SethPoulsen** [comment]
@ascholerChemeketa Thanks for catching this and fixing it. It was an easy thing for me to miss as I've only been working with proofs, not code most of the time.

**Pull request merged**
