### PR TITLE
Clean: Run Prettier.

### PR DESCRIPTION
**Pull request by bjones1**
This is to see if the tests work. Therefore, this PR only contains whitespaces changes.

### CODE REVIEW

**Comment by bjones1** [comment]
Oh, no -- unit tests are broken! This PR was a no-change test.

**Comment by bjones1** [comment]
Looks like hte failures are from fitb due to Sphinx 4.4.

**Comment by bnmnetp** [comment]
yes.. but I think you saw the comments in my PR that fix the problem with WARNINGS being elevated to ERRORs in sphinx 4.x

**Comment by bjones1** [comment]
I'll close this for now -- I assume your Sphinx PR will land soon and fix these?

**Pull request closed without merging**
